const BASE_URL = process.env.BASE_URL;
const RAZORPAY_KEY = process.env.RAZORPAY_KEY;
const AUTH_CLIENT_ID = process.env.AUTH_CLIENT_ID;
const RECAPTCHA_SITE_KEY = process.env.RECAPTCHA_SITE_KEY || '';
const RECAPTCHA_SITE_KEY_V2 = process.env.RECAPTCHA_SITE_KEY_V2 || '';
const ENCRYPT_VECTOR_KEY = process.env.ENCRYPT_VECTOR_KEY || '';
const ENCRYPT_PUBLIC_KEY =
  process.env.ENCRYPT_PUBLIC_KEY?.replace(/\\n/g, '\n') || '';
const MS_CLARITY_KEY = process.env.MS_CLARITY_KEY || '';
const GOOGLE_ANALYTICS_ID = process.env.GOOGLE_ANALYTICS_ID || '';
const GOOGLE_ADS_ID = process.env.GOOGLE_ADS_ID || '';
const GOOGLE_TAG_MANAGER_ID = process.env.GOOGLE_TAG_MANAGER_ID || '';
const META_PIXEL_ID = process.env.META_PIXEL_ID || '';

const FIREBASE_API = process.env.FIREBASE_API || '';
const FIREBASE_AUTH_DOMAIN = process.env.FIREBASE_AUTH_DOMAIN || '';
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID || '';
const FIREBASE_STORAGE_BUCKET = process.env.FIREBASE_STORAGE_BUCKET || '';
const FIREBASE_MESSAGING_SENDER_ID =
  process.env.FIREBASE_MESSAGING_SENDER_ID || '';
const FIREBASE_APP_ID = process.env.FIREBASE_APP_ID || '';
const FIREBASE_MEASUREMENT_ID = process.env.FIREBASE_MEASUREMENT_ID || '';

export {
  AUTH_CLIENT_ID,
  BASE_URL,
  ENCRYPT_PUBLIC_KEY,
  ENCRYPT_VECTOR_KEY,
  FIREBASE_API,
  FIREBASE_APP_ID,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_MEASUREMENT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET,
  GOOGLE_ADS_ID,
  GOOGLE_ANALYTICS_ID,
  GOOGLE_TAG_MANAGER_ID,
  META_PIXEL_ID,
  MS_CLARITY_KEY,
  RAZORPAY_KEY,
  RECAPTCHA_SITE_KEY,
  RECAPTCHA_SITE_KEY_V2,
};
