import {
  HomeIcon,
  LiveIcon,
  PlanExtensionIcon,
  QbankIcon,
  TestsIcon,
} from '@/elements/Icons';
import {
  AcademicCapIcon,
  BanknotesIcon,
  BookOpenIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  ClipboardDocumentCheckIcon,
  LinkIcon,
  MagnifyingGlassCircleIcon,
  MapPinIcon,
  Squares2X2Icon,
  TrophyIcon,
  UserCircleIcon,
} from '@heroicons/react/24/outline';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import forge from 'node-forge';

dayjs.extend(utc);

import {errorMessage} from '../constants';
import {ENCRYPT_PUBLIC_KEY, ENCRYPT_VECTOR_KEY, GOOGLE_ADS_ID} from './config';

import parse from 'html-react-parser';

import {IUserData} from '@/global/UserContext';
import {analytics} from '@/lib/firebase/initFirebase';
import {ISubscriptionSchema} from '@/types/pages.types';
import {logEvent} from 'firebase/analytics';

declare global {
  interface Window {
    gtag: any;
  }
}

export const buildErrorMessage = (errorObject: any): string => {
  if (typeof errorObject === 'string') {
    return errorObject;
  }
  // network error
  if (errorObject?.statusText?.includes('Network Error')) {
    return errorMessage.NETWORK_ERROR;
  } else if (errorObject?.response?.data?.detail) {
    return errorObject?.response?.data?.detail;
  } else if (errorObject?.response?.data?.message) {
    return errorObject?.response?.data?.message;
  } else if (
    !errorObject?.message ||
    errorObject?.message?.toLowerCase().includes('unexpected')
  ) {
    return errorMessage.SERVER_ERROR;
  } else if (
    errorObject?.message === 'Network request failed' ||
    errorObject?.statusText?.includes('Network Error')
  ) {
    return errorMessage.NETWORK_ERROR;
  } else if (errorObject?.message) {
    return errorObject.message;
  } else {
    return errorMessage.SERVER_ERROR;
  }
};

export const encrypt = (data: string) => {
  try {
    // Create a Forge public key using a PEM format
    const forgePublicKey = forge.pki.publicKeyFromPem(ENCRYPT_PUBLIC_KEY);
    // A random key generated by 16 bytes will use AES-128, 24 => AES-192, 32 => AES-256
    const randomKey = forge.random.getBytesSync(32);
    // An initialization vector (IV) is an arbitrary number that can be used with a secret key for data encryption to foil cyber attacks
    // The initialization vector (IV) converted to decode64
    const iv = forge.util.decode64(ENCRYPT_VECTOR_KEY);
    // A public key is used to encrypt data with RSAES-OAEP
    let encryptedKey = forgePublicKey.encrypt(randomKey.toString(), 'RSA-OAEP');
    // Encrypt some bytes using CBC mode
    const cipher = forge.cipher.createCipher('AES-CBC', randomKey);
    // Cipher starts with an initialization vector (IV)
    cipher.start({iv: iv});
    cipher.update(forge.util.createBuffer(data));
    cipher.finish();
    // Provides encrypted output
    const encrypted = cipher.output;
    // Convert data and keys to encode64
    const encodedData = forge.util.encode64(encrypted.data);
    const encodedKey = forge.util.encode64(encryptedKey);
    return {encodedKey, encodedData};
  } catch (error: any) {
    throw new Error(error.message);
  }
};

export const classNames = (...classes: (string | undefined | false | null)[]) => {
  return classes.filter(Boolean).join(' ');
};

export const getStyledParsedHTML = (html: string, _context?: string) => {
  if (!html || typeof html !== 'string') return null;
  return parse(html);
};

export const navbarLinks = (userRole: string) => {
  // Standard order for all user roles: Home → Tests → QBank → Profile → Plans → Plan Extension → Go to website
  const standardOrder = [
    {
      id: 245,
      title: 'Dashboard',
      url: '/',
      items: [],
      icon: <HomeIcon className="w-5" />,
    },
    {
      id: 9,
      title: 'Videos',
      url: '/videos',
      items: [],
      icon: <TestsIcon className="w-5" />,
    },
    {
      id: 81,
      title: 'Insights',
      url: '/insights',
      items: [
        {
          id: 811,
          title: 'Allotments',
          url: '/insights/allotments',
          items: [],
          icon: <LinkIcon className="w-4" />,
        },
        {
          id: 812,
          title: 'Closing Ranks',
          url: '/insights/closing-ranks',
          items: [],
          icon: <TrophyIcon className="w-4" />,
        },
        {
          id: 813,
          title: 'Seat Matrix',
          url: '/insights/seat-matrix',
          items: [],
          icon: <Squares2X2Icon className="w-4" />,
        },
        {
          id: 814,
          title: 'Fee, Stipend and Bond',
          url: '/insights/fee-stipend-bond',
          items: [],
          icon: <BanknotesIcon className="w-4" />,
        },
      ],
      icon: <QbankIcon className="w-5" />,
    },
    {
      id: 82,
      title: 'Tools',
      url: '/tools',
      items: [
        {
          id: 821,
          title: 'Allotment Mapping',
          url: '/tools/allotment-mapping',
          items: [],
          icon: <MapPinIcon className="w-4" />,
        },
        {
          id: 822,
          title: 'Rank Scan',
          url: '/tools/rank-scan',
          items: [],
          icon: <MagnifyingGlassCircleIcon className="w-4" />,
        },
      ],
      icon: <LiveIcon className="w-5" />,
    },
    {
      id: 7,
      title: 'Profile',
      url: '/user-profile',
      items: [],
      icon: <UserCircleIcon className="w-5" />,
    },
    {
      id: 5,
      title: 'Plans',
      url: '/plans',
      items: [],
      icon: <ClipboardDocumentCheckIcon className="w-5" />,
    },
    {
      id: 16,
      title: 'Explore',
      url: '/explore',
      items: [
        {
          id: 161,
          title: 'Institutes',
          url: '/explore/institutes',
          items: [],
          icon: <BuildingOffice2Icon className="w-4" />,
        },
        {
          id: 162,
          title: 'Universities',
          url: '/explore/universities',
          items: [],
          icon: <BuildingLibraryIcon className="w-4" />,
        },
        {
          id: 163,
          title: 'Counsellings',
          url: '/explore/counsellings',
          items: [],
          icon: <AcademicCapIcon className="w-4" />,
        },
        {
          id: 164,
          title: 'Courses',
          url: '/explore/courses',
          items: [],
          icon: <BookOpenIcon className="w-4" />,
        },
      ],
      icon: <PlanExtensionIcon />,
    },
    {
      id: 15,
      title: 'Resources',
      url: '/resources',
      items: [],
      icon: <PlanExtensionIcon />,
    },
  ];

  switch (userRole) {
    case 'student':
    case 'ambassador':
    case 'bdm':
      return standardOrder;
    default:
      return [];
  }
};

export const triggerGoogleConversionEvent = (payload: {
  amount: number;
  currency: string;
  razorpay_payment_id: string | number;
  PlanId: string | number;
}) => {
  // @ts-ignore
  window.gtag('event', 'conversion', {
    send_to: `${GOOGLE_ADS_ID}/O_pkCJ-F7cQZEMSDheo9`,
    value: payload.amount,
    currency: payload.currency,
    transaction_id: payload.razorpay_payment_id,
    PlanId: payload.PlanId,
  });
};

export const metaConversionEvent = (payload: {
  amount: number;
  currency: string;
  razorpay_payment_id: string | number;
  PlanId: string | number;
}) => {
  // @ts-ignore
  window.fbq('track', 'Purchase', {
    value: payload.amount,
    currency: payload.currency,
    content_ids: [payload.razorpay_payment_id, payload.PlanId],
  });
};

export const setGtagUserData = (userData: IUserData) => {
  const address = userData?.address_info?.length
    ? userData?.address_info[0]
    : null;

  window.gtag('set', 'user_data', {
    email: (userData.email ?? '').toLowerCase().trim(),
    phone_number: userData?.phone_number,
    ...(address
      ? {
          address: {
            first_name: (userData?.first_name ?? '').toLowerCase().trim(),
            last_name: (userData?.last_name ?? '').toLowerCase().trim(),
            street: (address?.address1 + ' ' + address?.address2)
              .toLowerCase()
              .trim(),
            city: (address?.city ?? '').toLowerCase().trim(),
            region: (address?.country_state ?? '').toLowerCase().trim(),
            postal_code: ((address?.pincode as string) ?? '')
              .toLowerCase()
              .trim(),
            country: address?.country,
          },
        }
      : {}),
  });
};

// Utility functions for subscription data
export const buildValidityDate = (startAt: string, duration: number) => {
  const endDate = dayjs
    .utc(startAt) // parse in UTC
    .add(duration, 'day') // add duration in days
    .format('DD MMM YYYY');
  const startDate = dayjs
    .utc(startAt) // parse in UTC
    .format('DD MMM YYYY');
  return `${startDate} - ${endDate}`;
};

export const hasAnyActiveSubscription = (
  subscriptions: ISubscriptionSchema[],
) => {
  if (!subscriptions || subscriptions.length === 0) {
    return false;
  }
  return subscriptions?.some(subscription =>
    isSubscriptionActive(subscription.start_at, subscription.duration),
  );
};
export const isSubscriptionActive = (startAt: Date, duration: number) => {
  const endDate = dayjs.utc(startAt).add(duration, 'day');
  return !dayjs().isAfter(endDate);
};

export const triggerAnalyticsEvent = (
  eventName: string,
  params: object = {} as object,
) => {
  try {
    if (!analytics) {
      return;
    }
    logEvent(analytics, eventName, {...params, os: 'WebApp'});
  } catch (error) {
    // Analytics event failed silently
  }
};
